INSERT INTO products 
(category_id, name, slug, short_description, description, price, sale_price, image, images, sku, stock_quantity, is_active, is_featured, sort_order, created_at, updated_at)
VALUES


(1,'Monstera Deliciosa','monstera-deliciosa','Grande plante tropicale décorative.','Plante très populaire aux feuilles perforées.',29.99,NULL,'images/products/monstera.jpg','["images/products/monstera_1.jpg"]','SKU-INT-001',50,1,0,1,NOW(),NOW()),
(1,'Pothos Doré','pothos-dore','Plante grimpante facile.','Tolère bien le manque de lumière.',14.90,NULL,'images/products/pothos.jpg',NULL,'SKU-INT-002',40,1,0,2,NOW(),NOW()),
(1,'Ficus Elastica','ficus-elastica','Plante robuste.','Feuilles épaisses et brillantes.',34.50,NULL,'images/products/ficus.jpg',NULL,'SKU-INT-003',20,1,0,3,NOW(),NOW()),
(1,'ZZ Plant','zz-plant','Très résistante.','Supporte très bien les environnements sombres.',24.90,19.90,'images/products/zzplant.jpg',NULL,'SKU-INT-004',60,1,1,4,NOW(),NOW()),
(1,'Calathea Orbifolia','calathea-orbifolia','Feuilles striées décoratives.','Magnifiques motifs naturels sur chaque feuille.',27.90,NULL,'images/products/calathea.jpg',NULL,'SKU-INT-005',30,1,0,5,NOW(),NOW()),
(1,'Spathiphyllum','spathiphyllum','Lys de la paix.','Plante élégante aux fleurs blanches pures.',19.90,NULL,'images/products/spathiphyllum.jpg',NULL,'SKU-INT-006',22,1,0,6,NOW(),NOW()),
(1,'Dracaena Marginata','dracaena-marginata','Plante élancée.','Apprécie les environnements lumineux.',22.90,NULL,'images/products/dracaena.jpg',NULL,'SKU-INT-007',33,1,0,7,NOW(),NOW()),
(1,'Philodendron Birkin','philodendron-birkin','Feuilles striées.','Très tendance dans les décorations modernes.',28.90,NULL,'images/products/birkin.jpg',NULL,'SKU-INT-008',15,1,0,8,NOW(),NOW()),
(1,'Areca Palm','areca-palm','Petit palmier intérieur.','Apporte une atmosphère tropicale douce.',39.90,NULL,'images/products/areca.jpg',NULL,'SKU-INT-009',12,1,1,9,NOW(),NOW()),
(1,'Sansevieria Laurentii','sansevieria-laurentii','Très résistante et dépolluante.','Parfaite pour les débutants.',18.50,NULL,'images/products/sansevieria.jpg',NULL,'SKU-INT-010',45,1,0,10,NOW(),NOW()),


(2,'Lavande Vraie','lavande-vraie','Fleur parfumée.','Idéale pour jardins secs et ensoleillés.',12.90,NULL,'images/products/lavande.jpg',NULL,'SKU-EXT-001',70,1,0,1,NOW(),NOW()),
(2,'Rosier Rouge','rosier-rouge','Fleur classique.','Très apprécié pour ses grosses fleurs rouges.',19.50,NULL,'images/products/rosier.jpg',NULL,'SKU-EXT-002',30,1,1,2,NOW(),NOW()),
(2,'Hortensia Bleu','hortensia-bleu','Arbuste fleuri.','Apprécie les sols acides et humides.',24.90,NULL,'images/products/hortensia.jpg',NULL,'SKU-EXT-003',20,1,0,3,NOW(),NOW()),
(2,'Bambou Fargesia','bambou-fargesia','Bambou non traçant.','Idéal pour haies et brise-vue.',39.90,NULL,'images/products/bambou.jpg',NULL,'SKU-EXT-004',12,1,0,4,NOW(),NOW()),
(2,'Géranium Rouge','geranium-rouge','Plante de balcon.','Floraison abondante en été.',9.99,NULL,'images/products/geranium.jpg',NULL,'SKU-EXT-005',60,1,0,5,NOW(),NOW()),
(2,'Olivier Nain','olivier-nain','Aspect méditerranéen.','Très décoratif sur terrasse.',49.90,NULL,'images/products/olivier.jpg',NULL,'SKU-EXT-006',10,1,1,6,NOW(),NOW()),
(2,'Yucca Rostrata','yucca-rostrata','Très résistant.','Supporte la chaleur extrême.',89.00,NULL,'images/products/yucca.jpg',NULL,'SKU-EXT-007',5,1,0,7,NOW(),NOW()),
(2,'Lavatera','lavatera','Floraison rose.','Apporte beaucoup de couleur.',14.90,NULL,'images/products/lavatera.jpg',NULL,'SKU-EXT-008',25,1,0,8,NOW(),NOW()),
(2,'Camélia Japonica','camelia-japonica','Fleurs élégantes.','Idéal pour les climats humides.',27.90,NULL,'images/products/camelia.jpg',NULL,'SKU-EXT-009',17,1,0,9,NOW(),NOW()),
(2,'Laurier Rose','laurier-rose','Résistant.','Supporte chaleur et sécheresse.',19.90,NULL,'images/products/laurier.jpg',NULL,'SKU-EXT-010',40,1,0,10,NOW(),NOW()),


(3,'Aloe Vera','aloe-vera','Succulente médicinale.','Connue pour ses propriétés apaisantes.',8.90,NULL,'images/products/aloe.jpg',NULL,'SKU-SUC-001',80,1,0,1,NOW(),NOW()),
(3,'Echeveria Blue','echeveria-blue','Rosette bleutée.','Très décorative et facile.',6.50,NULL,'images/products/echeveria.jpg',NULL,'SKU-SUC-002',60,1,0,2,NOW(),NOW()),
(3,'Haworthia Zebra','haworthia-zebra','Zébrures uniques.','Mini-succulente très appréciée.',5.99,NULL,'images/products/haworthia.jpg',NULL,'SKU-SUC-003',50,1,0,3,NOW(),NOW()),
(3,'Crassula Ovata','crassula-ovata','Arbre de jade.','Symbolise la prospérité.',12.90,NULL,'images/products/crassula.jpg',NULL,'SKU-SUC-004',35,1,0,4,NOW(),NOW()),
(3,'Sedum Morganianum','sedum-morganianum','Queue d’âne.','Succulente tombante spectaculaire.',13.90,NULL,'images/products/sedum.jpg',NULL,'SKU-SUC-005',28,1,0,5,NOW(),NOW()),
(3,'Lithops','lithops','Plantes-cailloux.','Imitent des pierres pour se protéger.',7.90,NULL,'images/products/lithops.jpg',NULL,'SKU-SUC-006',40,1,0,6,NOW(),NOW()),
(3,'Kalanchoe Blossfeldiana','kalanchoe-blossfeldiana','Fleurs colorées.','Très longue floraison.',9.99,NULL,'images/products/kalanchoe.jpg',NULL,'SKU-SUC-007',45,1,1,7,NOW(),NOW()),
(3,'Aeonium Arboreum','aeonium-arboreum','Rosaces sombres.','Forme un beau contraste décoratif.',14.90,NULL,'images/products/aeonium.jpg',NULL,'SKU-SUC-008',20,1,0,8,NOW(),NOW()),
(3,'Senecio Rowleyanus','senecio-rowleyanus','Plante collier de perles.','Très populaire en suspension.',16.90,NULL,'images/products/senecio.jpg',NULL,'SKU-SUC-009',18,1,0,9,NOW(),NOW()),
(3,'Gasteria Little Warty','gasteria-little-warty','Succulente rare.','Facile et résistante.',11.90,NULL,'images/products/gasteria.jpg',NULL,'SKU-SUC-010',25,1,0,10,NOW(),NOW()),


(4,'Basilic Grand Vert','basilic-grand-vert','Aromatique indispensable.','Parfait pour sauces et salades.',4.50,NULL,'images/products/basilic.jpg',NULL,'SKU-ARO-001',80,1,0,1,NOW(),NOW()),
(4,'Menthe Poivrée','menthe-poivree','Très parfumée.','Idéale pour infusions et desserts.',4.90,NULL,'images/products/menthe.jpg',NULL,'SKU-ARO-002',65,1,0,2,NOW(),NOW()),
(4,'Thym de Provence','thym-provence','Arôme intense.','Résiste très bien à la chaleur.',5.50,NULL,'images/products/thym.jpg',NULL,'SKU-ARO-003',70,1,0,3,NOW(),NOW()),
(4,'Romarin Officinal','romarin-officinal','Arbrisseau aromatique.','Très utilisé en cuisine méditerranéenne.',6.90,NULL,'images/products/romarin.jpg',NULL,'SKU-ARO-004',55,1,0,4,NOW(),NOW()),
(4,'Persil Frisé','persil-frise','Aromate polyvalent.','Pour garnitures et plats cuisinés.',3.90,NULL,'images/products/persil.jpg',NULL,'SKU-ARO-005',75,1,0,5,NOW(),NOW()),
(4,'Ciboulette','ciboulette','Saveur douce.','Idéale pour omelettes et sauces.',3.50,NULL,'images/products/ciboulette.jpg',NULL,'SKU-ARO-006',60,1,0,6,NOW(),NOW()),
(4,'Laurier Sauce','laurier-sauce','Feuilles aromatiques.','Indispensable pour bouquet garni.',7.90,NULL,'images/products/laurier-sauce.jpg',NULL,'SKU-ARO-007',30,1,0,7,NOW(),NOW()),
(4,'Sauge Officinale','sauge-officinale','Parfum intense.','Aromate ancien aux usages multiples.',6.50,NULL,'images/products/sauge.jpg',NULL,'SKU-ARO-008',40,1,0,8,NOW(),NOW()),
(4,'Origan','origan','Aromate italien.','Très utilisé sur les pizzas.',4.99,NULL,'images/products/origan.jpg',NULL,'SKU-ARO-009',45,1,0,9,NOW(),NOW()),
(4,'Estragon Français','estragon-francais','Saveur unique.','Parfum anisé très apprécié.',6.99,NULL,'images/products/estragon.jpg',NULL,'SKU-ARO-010',32,1,0,10,NOW(),NOW()),

(5,'Camomille Romaine','camomille-romaine','Infusions calmantes.','Plante médicinale traditionnelle.',5.90,NULL,'images/products/camomille.jpg',NULL,'SKU-MED-001',50,1,0,1,NOW(),NOW()),
(5,'Aloe Vera Médicinal','aloe-vera-medicinal','Gel cicatrisant.','Utilisé pour brûlures et irritations.',9.90,NULL,'images/products/aloe-med.jpg',NULL,'SKU-MED-002',45,1,0,2,NOW(),NOW()),
(5,'Mélisse','melisse','Infusions relaxantes.','Très parfumée et apaisante.',4.99,NULL,'images/products/melisse.jpg',NULL,'SKU-MED-003',60,1,0,3,NOW(),NOW()),
(5,'Gingembre','gingembre','Rhizome tonique.','Très utilisé en phytothérapie.',8.90,NULL,'images/products/gingembre.jpg',NULL,'SKU-MED-004',35,1,0,4,NOW(),NOW()),
(5,'Curcuma','curcuma','Anti-inflammatoire.','Ses racines sont très appréciées.',7.99,NULL,'images/products/curcuma.jpg',NULL,'SKU-MED-005',28,1,0,5,NOW(),NOW()),
(5,'Échinacée Pourpre','echinacee-pourpre','Renforce l’immunité.','Très populaire en herboristerie.',10.90,NULL,'images/products/echinacee.jpg',NULL,'SKU-MED-006',20,1,0,6,NOW(),NOW()),
(5,'Menthe Verte','menthe-verte','Digestive.','Plante aromatique et médicinale.',4.99,NULL,'images/products/menthe-verte.jpg',NULL,'SKU-MED-007',45,1,0,7,NOW(),NOW()),
(5,'Sauge Médicinale','sauge-medicinale','Antiseptique naturel.','Ancienne plante médicinale.',6.90,NULL,'images/products/sauge-med.jpg',NULL,'SKU-MED-008',30,1,0,8,NOW(),NOW()),
(5,'Tilleul','tilleul','Infusion calmante.','Apaisante et relaxante.',8.50,NULL,'images/products/tilleul.jpg',NULL,'SKU-MED-009',32,1,0,9,NOW(),NOW()),
(5,'Valériane','valeriane','Sommeil naturel.','Connue pour ses propriétés calmantes.',11.90,NULL,'images/products/valeriane.jpg',NULL,'SKU-MED-010',18,1,0,10,NOW(),NOW()),


(6,'Banana Musa','banana-musa','Grandes feuilles tropicales.','Plante spectaculaire en intérieur.',29.90,NULL,'images/products/bananier.jpg',NULL,'SKU-TRO-001',18,1,0,1,NOW(),NOW()),
(6,'Bird of Paradise','strelitzia-reginae','Fleur exotique.','Très décorative et imposante.',44.90,NULL,'images/products/strelitzia.jpg',NULL,'SKU-TRO-002',15,1,1,2,NOW(),NOW()),
(6,'Alocasia Polly','alocasia-polly','Feuilles en flèche.','Plante très graphique.',22.90,NULL,'images/products/alocasia.jpg',NULL,'SKU-TRO-003',20,1,0,3,NOW(),NOW()),
(6,'Caladium Pink','caladium-pink','Feuilles colorées.','Superbe plante décorative.',25.90,NULL,'images/products/caladium.jpg',NULL,'SKU-TRO-004',17,1,0,4,NOW(),NOW()),
(6,'Anthurium Rouge','anthurium-rouge','Fleur brillante.','Très élégante en intérieur.',34.90,NULL,'images/products/anthurium.jpg',NULL,'SKU-TRO-005',22,1,0,5,NOW(),NOW()),
(6,'Palmiers Kentia','kentia-palm','Palmier décoratif.','Apporte une ambiance tropicale.',49.90,NULL,'images/products/kentia.jpg',NULL,'SKU-TRO-006',10,1,1,6,NOW(),NOW()),
(6,'Ctenanthe Burle Marxii','ctenanthe-burle','Feuilles nervurées.','Convient aux intérieurs lumineux.',18.90,NULL,'images/products/ctenanthe.jpg',NULL,'SKU-TRO-007',28,1,0,7,NOW(),NOW()),
(6,'Ficus Lyrata','ficus-lyrata','Feuilles larges en forme de lyre.','Très prisée en déco moderne.',39.90,NULL,'images/products/lyrata.jpg',NULL,'SKU-TRO-008',12,1,1,8,NOW(),NOW()),
(6,'Calathea Triostar','calathea-triostar','Feuilles rouges et vertes.','Plante spectaculaire.',24.90,NULL,'images/products/triostar.jpg',NULL,'SKU-TRO-009',25,1,0,9,NOW(),NOW()),
(6,'Philodendron Imperial Red','philodendron-imperial-red','Feuilles rouges.','Variété tropicale impressionnante.',27.90,NULL,'images/products/imperialred.jpg',NULL,'SKU-TRO-010',18,1,0,10,NOW(),NOW()),


(7,'Pivoine Rose','pivoine-rose','Fleur volumineuse.','Appréciée pour ses grosses fleurs parfumées.',19.90,NULL,'images/products/pivoine.jpg',NULL,'SKU-VIV-001',30,1,1,1,NOW(),NOW()),
(7,'Iris Bleu','iris-bleu','Fleur graphique.','Très robuste au jardin.',12.50,NULL,'images/products/iris.jpg',NULL,'SKU-VIV-002',40,1,0,2,NOW(),NOW()),
(7,'Hémérocalle Jaune','hemerocalle','Fleur vibrante.','Très florifère et résistante.',14.90,NULL,'images/products/hemerocalle.jpg',NULL,'SKU-VIV-003',35,1,0,3,NOW(),NOW()),
(7,'Rudbeckia Gold','rudbeckia-gold','Fleur jaune éclatante.','Attire les pollinisateurs.',9.90,NULL,'images/products/rudbeckia.jpg',NULL,'SKU-VIV-004',50,1,0,4,NOW(),NOW()),
(7,'Aster Bleu','aster-bleu','Floraison tardive.','Parfait pour fin d’été.',8.90,NULL,'images/products/aster.jpg',NULL,'SKU-VIV-005',45,1,0,5,NOW(),NOW()),
(7,'Gaillarde','gaillarde','Fleur rouge et jaune.','Résiste très bien à la sécheresse.',7.90,NULL,'images/products/gaillarde.jpg',NULL,'SKU-VIV-006',60,1,0,6,NOW(),NOW()),
(7,'Campanule','campanule','Fleur délicate.','Très jolie en bordures.',6.90,NULL,'images/products/campanule.jpg',NULL,'SKU-VIV-007',50,1,0,7,NOW(),NOW()),
(7,'Coreopsis','coreopsis','Fleur jaune.','Floraison très longue.',5.90,NULL,'images/products/coreopsis.jpg',NULL,'SKU-VIV-008',55,1,0,8,NOW(),NOW()),
(7,'Lupin Rose','lupin-rose','Grandes hampes florales.','Idéal jardin cottage.',11.90,NULL,'images/products/lupin.jpg',NULL,'SKU-VIV-009',25,1,0,9,NOW(),NOW()),
(7,'Phlox Paniculata','phlox-paniculata','Fleur parfumée.','Très populaire dans les jardins.',13.90,NULL,'images/products/phlox.jpg',NULL,'SKU-VIV-010',20,1,0,10,NOW(),NOW()),


(8,'Pétunia Violet','petunia-violet','Très florifère.','Parfait pour balcon.',5.90,NULL,'images/products/petunia.jpg',NULL,'SKU-ANN-001',80,1,0,1,NOW(),NOW()),
(8,'Bégonia Rouge','begonia-rouge','Fleur brillante.','Aime l’ombre et l’humidité.',6.90,NULL,'images/products/begonia.jpg',NULL,'SKU-ANN-002',65,1,0,2,NOW(),NOW()),
(8,'Zinnia Mix','zinnia-mix','Couleurs variées.','Parfait pour massifs estivaux.',4.90,NULL,'images/products/zinnia.jpg',NULL,'SKU-ANN-003',50,1,0,3,NOW(),NOW()),
(8,'Souci Orange','souci-orange','Fleur vive.','Très facile à cultiver.',3.90,NULL,'images/products/souci.jpg',NULL,'SKU-ANN-004',70,1,0,4,NOW(),NOW()),
(8,'Tournesol Nain','tournesol-nain','Mini tournesol.','Très apprécié par les enfants.',7.90,NULL,'images/products/tournesol.jpg',NULL,'SKU-ANN-005',40,1,0,5,NOW(),NOW()),
(8,'Cosmos Blanc','cosmos-blanc','Fleur légère.','Très élégante.',4.99,NULL,'images/products/cosmos.jpg',NULL,'SKU-ANN-006',60,1,0,6,NOW(),NOW()),
(8,'Impatiens Rose','impatiens-rose','Aime l’ombre.','Très florifère en été.',6.50,NULL,'images/products/impatiens.jpg',NULL,'SKU-ANN-007',55,1,0,7,NOW(),NOW()),
(8,'Capucine','capucine','Fleur comestible.','Goût légèrement poivré.',4.50,NULL,'images/products/capucine.jpg',NULL,'SKU-ANN-008',45,1,0,8,NOW(),NOW()),
(8,'Verveine Rouge','verveine-rouge','Fleurs vibrantes.','Idéal jardinières.',5.50,NULL,'images/products/verveine.jpg',NULL,'SKU-ANN-009',48,1,0,9,NOW(),NOW()),
(8,'Gypsophile','gypsophile','Fleurs nuageuses.','Très utilisée en bouquets.',3.90,NULL,'images/products/gypsophile.jpg',NULL,'SKU-ANN-010',52,1,0,10,NOW(),NOW()),


(9,'Érable Japonais Rouge','erable-japonais-rouge','Feuillage rouge.','Très décoratif en jardin.',39.90,NULL,'images/products/erable.jpg',NULL,'SKU-ARB-001',22,1,1,1,NOW(),NOW()),
(9,'Buis Sphère','buis-sphere','Arbuste taillé.','Parfait pour entrées.',24.90,NULL,'images/products/buis.jpg',NULL,'SKU-ARB-002',30,1,0,2,NOW(),NOW()),
(9,'Magnolia Soulangeana','magnolia-soulangeana','Grandes fleurs roses.','Arbre d’ornement très apprécié.',49.90,NULL,'images/products/magnolia.jpg',NULL,'SKU-ARB-003',15,1,0,3,NOW(),NOW()),
(9,'Cornouiller Blanc','cornouiller-blanc','Bois rouge décoratif.','Très beau en hiver.',29.90,NULL,'images/products/cornouiller.jpg',NULL,'SKU-ARB-004',18,1,0,4,NOW(),NOW()),
(9,'Forsythia','forsythia','Fleurs jaunes.','Annonce le printemps.',17.90,NULL,'images/products/forsythia.jpg',NULL,'SKU-ARB-005',40,1,0,5,NOW(),NOW()),
(9,'Viorne Obier','viorne-obier','Boules blanches.','Arbuste apprécié en massif.',19.90,NULL,'images/products/viorne.jpg',NULL,'SKU-ARB-006',32,1,0,6,NOW(),NOW()),
(9,'Albizia','albizia','Arbre à soie.','Fleurs roses plumeuses.',34.90,NULL,'images/products/albizia.jpg',NULL,'SKU-ARB-007',12,1,1,7,NOW(),NOW()),
(9,'Laurier du Portugal','laurier-portugal','Arbuste dense.','Idéal haies résistantes.',21.90,NULL,'images/products/laurier-portugal.jpg',NULL,'SKU-ARB-008',40,1,0,8,NOW(),NOW()),
(9,'Chêne Vert','chene-vert','Arbre robuste.','Très résistant au climat chaud.',55.90,NULL,'images/products/chenevert.jpg',NULL,'SKU-ARB-009',10,1,0,9,NOW(),NOW()),
(9,'Arbre aux Papillons','arbre-papillons','Attire les papillons.','Arbuste parfumé très florifère.',14.90,NULL,'images/products/buddleia.jpg',NULL,'SKU-ARB-010',50,1,0,10,NOW(),NOW()),
(10,'Jasmin Étoilé','jasmin-etoile','Fleurs blanches parfumées.','Croissance rapide.',19.90,NULL,'images/products/jasmin.jpg',NULL,'SKU-GRI-001',35,1,1,1,NOW(),NOW()),
(10,'Glycine Violette','glycine-violette','Longs grappes fleuries.','Plante spectaculaire.',34.90,NULL,'images/products/glycine.jpg',NULL,'SKU-GRI-002',20,1,0,2,NOW(),NOW()),
(10,'Clématite Rose','clematite-rose','Fleurs délicates.','Idéale pergola et treillis.',22.90,NULL,'images/products/clematite.jpg',NULL,'SKU-GRI-003',28,1,0,3,NOW(),NOW()),
(10,'Lierre Vert','lierre-vert','Très résistant.','Grimpante persistante.',12.90,NULL,'images/products/lierre.jpg',NULL,'SKU-GRI-004',60,1,0,4,NOW(),NOW()),
(10,'Passiflore Bleue','passiflore-bleue','Fleur exotique.','Grimpante rapide.',24.90,NULL,'images/products/passiflore.jpg',NULL,'SKU-GRI-005',18,1,0,5,NOW(),NOW()),
(10,'Chèvrefeuille','chevrefeuille','Très parfumé.','Attire les pollinisateurs.',17.90,NULL,'images/products/chevrefeuille.jpg',NULL,'SKU-GRI-006',25,1,0,6,NOW(),NOW()),
(10,'Bougainvillier Rose','bougainvillier-rose','Très coloré.','Plante méditerranéenne.',29.90,NULL,'images/products/bougainvillier.jpg',NULL,'SKU-GRI-007',15,1,0,7,NOW(),NOW()),
(10,'Rosier Grimpant Rouge','rosier-grimpant-rouge','Fleurs rouges.','Grimpante classique.',21.90,NULL,'images/products/rosier-grimpant.jpg',NULL,'SKU-GRI-008',22,1,0,8,NOW(),NOW()),
(10,'Vigne Vierge','vigne-vierge','Feuillage rouge en automne.','Très rapide.',13.90,NULL,'images/products/vigne.jpg',NULL,'SKU-GRI-009',40,1,0,9,NOW(),NOW()),
(10,'Ipomée Bleue','ipomee-bleue','Fleur en trompette.','Grimpante annuelle douce.',7.90,NULL,'images/products/ipomee.jpg',NULL,'SKU-GRI-010',55,1,0,10,NOW(),NOW());